delivery/delivery/ext/site/main.py
from flask import Blueprint, current_app, render_template

bp = Blueprint("site", __name__)


@bp.route("/")
def index():
    print("entrei na funcao main")
    current_app.logger.debug("Entrei na funcao main")
    return render_template("index.html")


@bp.route("/sobre")
def about():
    return render_template("about.html")


@bp.route("/restaurantes")
def restaurants():
    return render_template("restaurants.html")

delivery/delivery/templates/about.html
{% extends "base.html" %}

{% block top %}
<section class="hero is-primary">
<div class="hero-body">
    <div class="container">
        <h1>CodeFoods</h1>
    </div>
</div>
</section>
{% endblock %}


{% block main %}
<p>

    O melhor site de delivery
    de comida #vegan do mundo! da twitch!
    e do universo!!!!

</p>
{% endblock %}

delivery/delivery/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    {% endblock head %}
    
    {%block  extra_css %} {% endblock extra_css %}
</head>
  <body>
      

    {% block nav %}
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="https://bulma.io">
            <strong>CodeFoods</strong>
          </a>
      
          <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
      
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item" href="/">
              Home
            </a>
      
            <a class="navbar-item" href="{{ url_for('site.restaurants') }}">
              Restaurantes
            </a>

            <a class="navbar-item" href="{{ url_for('site.about') }}">
              Sobre
            </a>
      
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                More
              </a>
      
              <div class="navbar-dropdown">
                <a class="navbar-item">
                  Pizza
                </a>
                <a class="navbar-item">
                  Pastel
                </a>
                <a class="navbar-item">
                  Hamburguer
                </a>
                <hr class="navbar-divider">
                <a class="navbar-item">
                  Report an issue
                </a>
              </div>
            </div>
          </div>
      
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <a class="button is-primary">
                  <strong>Sign up</strong>
                </a>
                <a class="button is-light">
                  Log in
                </a>
              </div>
            </div>
          </div>
        </div>
      </nav>
    {% endblock nav%}

    {% block top%}{% endblock top %}



  <section class="section">
    <div class="container">
        {% block main %}{% endblock main%}
    </div>
  </section>

  {% block footer %}
  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
        <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
        is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
      </p>
    </div>
  </footer>

    {% endblock footer%}
  </body>
</html>

delivery/delivery/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CodeShow Foods Delivery</title>
</head>
<body>

    <h1>Pagina inicial do site</h1>

</body>
</html>

delivery/delivery/templates/restaurants.html
{% extends "base.html" %}
{% import "macros/list_item.html" as list_item %}

{% block top %}
<section class="hero is-primary">
<div class="hero-body">
    <div class="container">
    <h1 class="title">
        {{ site_name }}
    </h1>
    <h2 class="subtitle">
        {{ site_subtitle }}
    </h2>
    </div>
</div>
</section>
{% endblock top %}



{% block main %}
<div class="columns">
    {{ list_item.cards([1, 2, 3, 4, 5, 6, 7, 8]) }}
</div>
{% endblock main %}